# -*- coding: utf-8 -*-
"""Bagging_RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4ltb_cjjWvB7uIT5o6tpqAjTtAMvkp-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('train.csv')

df.head()

df.columns

l1=['PassengerId','Cabin','Ticket']

df.drop(l1,inplace=True,axis=1)

df.head()

df.shape

l2=['Name']
df.drop(l2,axis=1,inplace=True)

df.isnull().sum()

df['Age']=df['Age'].fillna(df['Age'].mean())
emb=df['Embarked'].mode()
df['Embarked']=df['Embarked'].fillna(emb[0])

df.isnull().sum()

df.head()

from sklearn.preprocessing import LabelEncoder
le_sex=LabelEncoder()
le_emb=LabelEncoder()
le_newName=LabelEncoder()

df['Sex']=le_sex.fit_transform(df['Sex'])
df['Embarked']=le_emb.fit_transform(df['Embarked'])

df.head(

)

X=df.iloc[:,1:].values
y=df.iloc[:,0].values

X.shape,y.shape

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

pred=clf.predict(X_test)

clf.score(X_train,y_train)

clf.score(X_test,y_test)

from sklearn.metrics import confusion_matrix

print(confusion_matrix(pred,y_test))