# -*- coding: utf-8 -*-
"""Boosting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GxXz7IqXSxs4krpBmHCU5vk-1_2dlyYT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('train.csv')

df.head()

df.columns

l1=['PassengerId','Cabin','Ticket']

df.drop(l1,inplace=True,axis=1)

df.head()

df.shape

l2=['Name']
df.drop(l2,axis=1,inplace=True)

df.isnull().sum()

df['Age']=df['Age'].fillna(df['Age'].mean())
emb=df['Embarked'].mode()
df['Embarked']=df['Embarked'].fillna(emb[0])

df.isnull().sum()

df.head()

from sklearn.preprocessing import LabelEncoder
le_sex=LabelEncoder()
le_emb=LabelEncoder()
le_newName=LabelEncoder()

df['Sex']=le_sex.fit_transform(df['Sex'])
df['Embarked']=le_emb.fit_transform(df['Embarked'])

df.head(

)

X=df.iloc[:,1:].values
y=df.iloc[:,0].values

X.shape,y.shape

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test
                    )

from sklearn.ensemble import AdaBoostClassifier

clf=AdaBoostClassifier(n_estimators=10);

clf.fit(X_train,y_train)

pred=clf.predict(X_test)

clf.score(X_train,y_train)

clf.score(X_test,y_test)

from sklearn.metrics import confusion_matrix
con=confusion_matrix(y_test,pred)

print(con)

from xgboost import XGBClassifier
clf2=XGBClassifier()

clf2.fit(X_train,y_train)

pred2=clf2.predict(X_test)

clf2.score(X_train,y_train)

clf2.score(X_test,y_test)

print(confusion_matrix(y_test,pred2))

from sklearn.metrics import classification_report
print(classification_report(y_test,pred2))

from sklearn.model_selection import cross_val_score

cross_val_score(clf,X_train,y_train,cv=5).mean()

#hyper paraeter tuning
from sklearn.model_selection import GridSearchCV

param={
    "learning_rate":[0.1,0.01,0.3,0.6,0.5],
    "max_depth":[1,2,3,4],
    "n_estimators":[5,10,15,20]
}

clf_grid=GridSearchCV(estimator=clf2,param_grid=param,cv=5,n_jobs=-1)

clf_grid.fit(X_train,y_train)

clf_grid.best_estimator_

clf_grid.best_estimator_.score(X_test,y_test)

clf_grid.best_params_

clf_grid.best_score_