# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUq6ZFGw1C2ORXZiJE2RA3yklfUqA7ZA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)

df.head()

df.shape

df['species'] = [iris.target_names[i] for i in iris.target]
df.head()

df.columns

df.shape

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

X = df.iloc[:, 0:4]
Y = df.iloc[:, 4]
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

X_train.shape,Y_train.shape,X_test.shape,Y_test.shape

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

from sklearn.tree import DecisionTreeClassifier

clf=DecisionTreeClassifier(criterion='entropy',max_depth=3,random_state=0)

clf.fit(X_train,Y_train)

y_pred=clf.predict(X_train)

clf.score(X_train,Y_train)

clf.score(X_test,Y_test)

"""# Random Forest"""

from sklearn.ensemble import RandomForestClassifier
clf1=RandomForestClassifier(n_estimators=100,criterion='entropy',max_depth=3,random_state=0)

clf1.fit(X_train,Y_train)

pred_y1=clf1.predict(X_train)

clf1.score(X_train,Y_train)

clf1.score(X_test,Y_test)