# -*- coding: utf-8 -*-
"""Kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2Lf_EkIMxT4xbDwAYfDm_cq5zufHc_Q
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

img =plt.imread("/content/college.jpg") #rbg

plt.imshow(img)
plt.show()

img.shape

type(img)

img1=cv2.imread("/content/college.jpg")
img1=cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)

plt.imshow(img1)
plt.show()

all_pixel=img.reshape(1200*1599,3)
all_pixel.shape

from sklearn.cluster import KMeans
km=KMeans(n_clusters=50)

km.fit(all_pixel)

centre=km.cluster_centers_
centre

centre=np.array(centre,dtype='uint')
centre

np.unique(km.labels_,return_counts=True)

new_img=np.zeros((all_pixel.shape[0],3),dtype='uint')

plt.imshow(new_img.reshape(1200,1599,3))
plt.show()

for i in range(new_img.shape[0]):
  new_img[i]=centre[km.labels_[i]]

plt.imshow(new_img.reshape(1200,1599,3))
plt.show()