# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXcA3TBqpkcanLRE9t1GoxoSCC1aD8OB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

X=pd.read_csv('xdata.csv',header=None)
Y=pd.read_csv('ydata.csv',header=None)

X.columns =["S.no","x1","x2"]
X.head()

Y.columns=["S.no","target"]
Y.head()

X=X.iloc[:,1:].values
Y=Y.iloc[:,1:].values
X.shape,Y.shape

plt.scatter(X[:,0],X[:,1],c=Y[:,0])
plt.show()

testing_point =np.array([4.2,4])
plt.scatter(testing_point[0],testing_point[1],c="red")
plt.scatter(X[:,0],X[:,1],c=Y[:,0])
plt.show()

def distance(x1,x2):
  return np.sqrt(sum((x1-x2)**2))

k=100

# step 1
vals=[]

for i in range(X.shape[0]):
  dist=distance(X[i],testing_point)
  vals.append([dist,Y[i][0]])
# step 2
vals=sorted(vals)
vals=vals[:k]
vals=np.array(vals)
# print(vals)

new_val=np.unique(vals[:,1],return_counts=True)
print(new_val)#new_val tells which classes are present among the k-nearest neighbors and how many times each class appears
index=new_val[1].argmax()
print(index) # index where maximum value is present
ans=new_val[0][index]
print(ans)

# final function
def knn(X,Y,testing_point,k):
  vals=[]
  m=X.shape[0]
  for i in range(m):
    dist=distance(X[i],testing_point)
    vals.append([dist,Y[i][0]])
  vals=sorted(vals)
  vals=vals[:k]
  vals=np.array(vals)
  new_val=np.unique(vals[:,1],return_counts=True)
  index=new_val[1].argmax()
  ans=new_val[0][index]
  return ans

testing_point =np.array([1,4])
print(knn(X,Y,testing_point,7))