# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ew0PjtMZjmrKMFQ0BWpMOUJLiSbFmrre

#Linear Regression
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

X=pd.read_csv('/content/Linear_X_Train.csv')
Y=pd.read_csv('/content/Linear_Y_Train.csv')

plt.scatter(X.values,Y.values,c='b')
plt.show()

X = X.values
Y = Y.values

def step_gd(X,Y,learning_rate,m,c):
  m_slope,c_slope=0,0
  N=X.shape[0]
  for i in range(N):
      x=X[i]
      y=Y[i]
      m_slope+=(-2/N)*(y-m*x-c)*x
      c_slope+=(-2/N)*(y-m*x-c)
      new_m=m-learning_rate*m_slope
      new_c=c-learning_rate*c_slope
  return new_m,new_c

def gd(X,Y,num_itr,learning_rate):
  m=0
  c=0
  for i in range(num_itr):
    m,c=step_gd(X,Y,learning_rate,m,c)
  return m,c

def run(X,Y):
  num_inter=300
  learning_rate=0.01
  m,c=gd(X,Y,num_inter,learning_rate)
  return m,c

m,c=run(X,Y)

m,c

pred_y=[]
for i in range (X.shape[0]):
  pred_y.append(m*X[i]+c)

# pred_y

plt.scatter(X,Y,c='b')
plt.plot(X,pred_y,c='r')
plt.show()