# -*- coding: utf-8 -*-
"""Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WjFyRMo6Kza1-9xWsXpkUl8fMJrI8i5m

# **Logistic** **Regession**

## IN Logistic Regression , we have Sigmoid Function as our Hypothesis
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded=files.upload()
print(uploaded)

X_train=pd.read_csv("/content/train.csv")

X_train.head()

X_train.columns

l1=['PassengerId','Name','Ticket','Cabin']

X_train.drop(l1,axis=1,inplace=True)

X_train.info()

X_train.isnull().sum()

X_train["Age"].fillna(X_train["Age"].mean(),inplace=True)
X_train["Embarked"].fillna("S",inplace=True)

X_train['Embarked'].mode()

X_train.isnull().sum()

X_train.shape

X_train.head()

from sklearn.preprocessing import LabelEncoder
le_g=LabelEncoder()
le_e=LabelEncoder()

X_train["Sex"]=le_g.fit_transform(X_train["Sex"])
X_train["Embarked"]=le_e.fit_transform(X_train["Embarked"])

X_train.head()

X=X_train.iloc[:,1:].values
Y=X_train.iloc[:,0].values

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

X[:5]

"""Data
 ↓
Clean Missing Values
 ↓
Encode Categorical Data
 ↓
Feature Scaling
 ↓
Apply Sigmoid Function
 ↓
Binary Output (0 or 1)

"""

from sklearn.linear_model import LogisticRegression

"""| Solver    | Dataset Size | L1 | L2 | Multiclass |
| --------- | ------------ | -- | -- | ---------- |
| liblinear | Small        | ✅  | ✅  | ❌          |
| lbfgs     | Medium       | ❌  | ✅  | ✅          |
| sag       | Large        | ❌  | ✅  | ✅          |
| saga      | Large        | ✅  | ✅  | ✅          |
| newton-cg | Medium       | ❌  | ✅  | ✅          |

"""

clf=LogisticRegression(solver='sag',random_state=0) #A solver is the algorithm used to find optimal weights (w, b)
# by minimizing log-loss (cost function)
clf.fit(X,Y)

Y_pred=clf.predict(X)

clf.score(X,Y)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y,Y_pred)
print(cm)  #[[TN  FP]
            #[FN  TP]]