# -*- coding: utf-8 -*-
"""MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqdTqifr24IeQoE9zIocu45ESpe9j0tt
"""

! pip install -q kaggle
from google.colab import files
files.upload()

! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

#!/bin/bash
!kaggle datasets download oddrationale/mnist-in-csv

!unzip /content/mnist-in-csv.zip

"""START

mnist IS A image data where digits are written . it is hello world of ML
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

df=pd.read_csv('/content/mnist_train.csv')

df.head()

df.shape

def image_plot(x):
  x=x.reshape(28,28)
  plt.imshow(x,cmap="gray")

test=df.values
image_plot(test[2][1:])

X_train=df.iloc[:,1:].values
y_train=df.iloc[:,0].values
X_train.shape,y_train.shape

image_plot(X_train[109])

y_train[109]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_train,y_train,test_size=0.2,random_state=0)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

def distance(x1,x2):
  return np.sqrt(sum((x1-x2)**2))

def knn(X,Y,testing_point,k=7):
  vals=[]
  m=X.shape[0]
  for i in range(m):
    dist=distance(X[i],testing_point)
    vals.append([dist,Y[i]])
  vals=sorted(vals)
  vals=vals[:k]
  vals=np.array(vals)
  new_val=np.unique(vals[:,1],return_counts=True)
  index=new_val[1].argmax()
  ans=new_val[0][index]
  return ans

pred=[]

for i in tqdm(range(20)):
  pred.append(knn(X_train,y_train,X_test[i]))

from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors=7,n_jobs=-1)
clf.fit(X_train,y_train)

pred2=clf.predict(X_test[:20])

pred

pred2

(pred==pred2).sum()

y_test

(pred2==y_test[:20])

(pred2==y_test[:20]).sum()

(pred2==y_test[:20]).sum()/20

"""#evaluation matrix"""

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test[:20],pred2) #labels=["0","1"."2",..,"9"]