# -*- coding: utf-8 -*-
"""MultiFeatureLinear_Reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iK69NqB1m7nidBsldgN38AFLA0oWd5YY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

! pip install -q kaggle
from google.colab import files
files.upload()

! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

#!/bin/bash
!kaggle datasets download puxama/bostoncsv

!unzip /content/bostoncsv.zip

housing = pd.read_csv('/content/Boston.csv')

df_housing = housing.select_dtypes(include=[np.number])

# . Create correlation heatmap
plt.figure(figsize=(8, 12))
sns.heatmap(df_housing.corr(), annot=True, cmap="coolwarm")
plt.show()

sns.pairplot(housing)
plt.show()

housing.head()

X = housing.iloc[:,1:14].values   # (506, 13)
Y = housing['medv'].values                # (506,)

print(X.shape)
print(Y.shape)

X

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, Y_train)

Y_pred = lr.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

print("MSE:", mean_squared_error(Y_test, Y_pred))
print("R2 Score:", r2_score(Y_test, Y_pred))

plt.scatter(Y_test, Y_pred, c='b')
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.plot([Y_test.min(), Y_test.max()],
         [Y_test.min(), Y_test.max()],
         c='r')
plt.grid(True)
plt.show()