# -*- coding: utf-8 -*-
"""SalaryData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbIQGFn2EXNxKnxo4TcTKwLJr04HeV8j
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = {
    "YearsExperience": [
        1.1, 1.3, 1.5, 2.0, 2.2, 2.9, 3.0, 3.2, 3.2, 3.7,
        3.9, 4.0, 4.0, 4.1, 4.5, 4.9, 5.1, 5.3, 5.9, 6.0,
        6.8, 7.1, 7.9, 8.2, 8.7, 9.0, 9.5, 9.6, 10.3, 10.5
    ],
    "Salary": [
        39343, 46205, 37731, 43525, 39891, 56642, 60150, 54445, 64445, 57189,
        63218, 55794, 56957, 57081, 61111, 67938, 66029, 83088, 81363, 93940,
        91738, 98273, 101302, 113812, 109431, 105582, 116969, 112635, 122391, 121872
    ]
}

df = pd.DataFrame(data)

# Save CSV
path = "/content/Salary_Data.csv"
df.to_csv(path, index=False)

path

df=pd.read_csv('/content/Salary_Data.csv')

X=df.iloc[:,0:1].values  #sklearn requires X to be 2D .ecause ML models support multiple features, so input is always matrix.
Y=df.iloc[:,1].values

X.shape,Y.shape

plt.scatter(X,Y)
plt.show()

from sklearn.linear_model import LinearRegression

reg=LinearRegression()
reg.fit(X,Y)

y_pred=reg.predict(X)

plt.scatter(X,Y)
plt.plot(X,y_pred)
plt.show()